

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: bd_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,b
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,q

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            -Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}











server:
  port: 10001
