
server:
  port: 10005

spring:
  application:
    name: iplay-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.138.29:3306/gulimall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      #初始化连接池大小
      initial-size: 5
      #最小连接数
      min-idle: 10
      #最大连接数
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久进行一次检测，检测需要关闭的空闲连接，单位毫秒。
      time-between-eviction-runs-millis: 2000
      #配置一个连接在连接池中的最小生存时间，单位毫秒
      min-evictable-idle-time-millis: 600000
      #配置一个连接在连接池中的最大生存时间，单位毫秒
      max-evictable-idle-time-millis: 900000
      #用来检测连接是否有效
      validation-query: select 1
      test-while-idle: true
      #配置从连接池获取连接时，是否检查连接有效性，true每次都检查；false不检查。
      test-on-borrow: false
      # 配置向连接池归还连接时，是否检查连接有效性，true每次都检查；false不检查
      test-on-return: false
      #连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作
      keep-alive: true
      #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
      #监控统计用的filter:stat
      #日志用的filter:log4j
      #防御sql注入的filter:wall
      filter: stat
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848






mybatis-plus:
  global-config:
    db-config:
      id-type: auto



name: hinz
age: 25



